/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aula18_Desafio.Telas;

import Aula18_Desafio.Util.CadastroUsuarios;
import Aula18_Desafio.Util.Usuarios;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaNovoUsuário extends javax.swing.JFrame {

    /**
     * Creates new form TelaNovoUsuário
     */
    public TelaNovoUsuário() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pblBase = new javax.swing.JPanel();
        pnlDados = new javax.swing.JPanel();
        lblNomeUsuario = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pwfSenha = new javax.swing.JPasswordField();
        lblConfirmaSenha = new javax.swing.JLabel();
        pwfConfirmaSenha = new javax.swing.JPasswordField();
        pnlBotoes = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        pnlLogotipo = new javax.swing.JPanel();
        lblLogotipo = new javax.swing.JLabel();
        pnlSaudacao = new javax.swing.JPanel();
        lblSaudacao1 = new javax.swing.JLabel();
        lblSaudacao2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        pblBase.setBackground(new java.awt.Color(11, 11, 37));
        pblBase.setForeground(new java.awt.Color(255, 255, 255));

        pnlDados.setBackground(new java.awt.Color(11, 11, 37));
        pnlDados.setForeground(new java.awt.Color(255, 255, 255));
        pnlDados.setLayout(new java.awt.GridLayout(8, 1, 3, 3));

        lblNomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeUsuario.setText("Insira o seu nome:");
        pnlDados.add(lblNomeUsuario);

        txtNomeUsuario.setBackground(new java.awt.Color(153, 0, 204));
        txtNomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        pnlDados.add(txtNomeUsuario);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Insira o username:");
        pnlDados.add(lblUsername);

        txtUsername.setBackground(new java.awt.Color(153, 0, 204));
        txtUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        pnlDados.add(txtUsername);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Insira a senha:");
        pnlDados.add(lblSenha);

        pwfSenha.setBackground(new java.awt.Color(153, 0, 204));
        pwfSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pwfSenha.setForeground(new java.awt.Color(255, 255, 255));
        pwfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwfSenhaActionPerformed(evt);
            }
        });
        pnlDados.add(pwfSenha);

        lblConfirmaSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblConfirmaSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmaSenha.setText("Confirme sua senha:");
        pnlDados.add(lblConfirmaSenha);

        pwfConfirmaSenha.setBackground(new java.awt.Color(153, 0, 204));
        pwfConfirmaSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pwfConfirmaSenha.setForeground(new java.awt.Color(255, 255, 255));
        pwfConfirmaSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwfConfirmaSenhaFocusLost(evt);
            }
        });
        pnlDados.add(pwfConfirmaSenha);

        pnlBotoes.setBackground(new java.awt.Color(11, 11, 37));
        pnlBotoes.setForeground(new java.awt.Color(255, 255, 255));
        pnlBotoes.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        btnCancelar.setBackground(new java.awt.Color(6, 142, 182));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnCancelar);

        btnCadastrar.setBackground(new java.awt.Color(6, 142, 182));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnCadastrar);

        pnlLogotipo.setBackground(new java.awt.Color(11, 11, 37));
        pnlLogotipo.setForeground(new java.awt.Color(255, 255, 255));

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aula18_Desafio/Imagens/icons8-usuário-homem-com-círculo-100.png"))); // NOI18N

        pnlSaudacao.setBackground(new java.awt.Color(11, 11, 37));
        pnlSaudacao.setForeground(new java.awt.Color(255, 255, 255));

        lblSaudacao1.setForeground(new java.awt.Color(255, 255, 255));
        lblSaudacao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaudacao1.setText("Insira os seus dados abaixo ");

        lblSaudacao2.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblSaudacao2.setForeground(new java.awt.Color(255, 255, 255));
        lblSaudacao2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaudacao2.setText("Novo usuário");

        javax.swing.GroupLayout pnlSaudacaoLayout = new javax.swing.GroupLayout(pnlSaudacao);
        pnlSaudacao.setLayout(pnlSaudacaoLayout);
        pnlSaudacaoLayout.setHorizontalGroup(
            pnlSaudacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSaudacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSaudacao1)
                .addGap(36, 36, 36))
            .addGroup(pnlSaudacaoLayout.createSequentialGroup()
                .addComponent(lblSaudacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlSaudacaoLayout.setVerticalGroup(
            pnlSaudacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSaudacaoLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblSaudacao2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaudacao1)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout pnlLogotipoLayout = new javax.swing.GroupLayout(pnlLogotipo);
        pnlLogotipo.setLayout(pnlLogotipoLayout);
        pnlLogotipoLayout.setHorizontalGroup(
            pnlLogotipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogotipoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblLogotipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSaudacao, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnlLogotipoLayout.setVerticalGroup(
            pnlLogotipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogotipoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlLogotipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlSaudacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogotipo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pblBaseLayout = new javax.swing.GroupLayout(pblBase);
        pblBase.setLayout(pblBaseLayout);
        pblBaseLayout.setHorizontalGroup(
            pblBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pblBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pblBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlLogotipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pblBaseLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pblBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
        );
        pblBaseLayout.setVerticalGroup(
            pblBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLogotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDados, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pblBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pblBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pwfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwfSenhaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        TelaLogin telaInicial = null;
        try {
            telaInicial = new TelaLogin();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaNovoUsuário.class.getName()).log(Level.SEVERE, null, ex);
        }
        telaInicial.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        try {

            //Validação de senha
            String senha = new String(pwfSenha.getPassword());
            String confirmaSenha = new String(pwfConfirmaSenha.getPassword());

            if (!senha.equals(confirmaSenha)) {
                String mensagem = "As duas senhas devem ser iguais!";
                JOptionPane.showMessageDialog(null, mensagem);
                pwfConfirmaSenha.setText("");
                pwfConfirmaSenha.grabFocus();
            } else {
                btnCadastrar.setEnabled(true);
                //Captura informações na tela
                String nomeCompleto = txtNomeUsuario.getText();
                String username = txtUsername.getText();
                //String senha = new String(pwfSenha.getPassword());
                //Instancia objetos e insere item no Array
                Usuarios novoItem = new Usuarios(nomeCompleto, username, senha);
                CadastroUsuarios op = new CadastroUsuarios();
                op.insereUsuarioBanco(novoItem);
                
                
            }

        } catch (Exception e) {
            // Tratamento de Exceções
            String mensagem = "Erro ao insanciar e/ou cadastrar novo usuário";
            JOptionPane.showMessageDialog(null, mensagem);
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void pwfConfirmaSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwfConfirmaSenhaFocusLost


    }//GEN-LAST:event_pwfConfirmaSenhaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoUsuário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoUsuário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoUsuário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoUsuário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovoUsuário().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblConfirmaSenha;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblSaudacao1;
    private javax.swing.JLabel lblSaudacao2;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pblBase;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPanel pnlLogotipo;
    private javax.swing.JPanel pnlSaudacao;
    private javax.swing.JPasswordField pwfConfirmaSenha;
    private javax.swing.JPasswordField pwfSenha;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
