/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aula13;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaAula13 extends javax.swing.JFrame {

    /**
     * Creates new form FrameAula13
     */
    //Método construtor da tela
    public TelaAula13() {
        initComponents();
        rbtnJava.setSelected(true); // Inicializa o RadioButton Java marcado
                                      //Quando inicializado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        rbtnJava = new javax.swing.JRadioButton();
        rbtnJavaScript = new javax.swing.JRadioButton();
        lblTitulo = new javax.swing.JLabel();
        btnConferir = new javax.swing.JButton();
        rbtnPython = new javax.swing.JRadioButton();
        rbtnCSharp = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbtnJava.setText("Java");
        rbtnJava.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnJavaStateChanged(evt);
            }
        });

        rbtnJavaScript.setText("JavaScript");
        rbtnJavaScript.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnJavaScriptStateChanged(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Qual é  a melhor linguagem de programação do mundo?");

        btnConferir.setText("Conferir!");
        btnConferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConferirActionPerformed(evt);
            }
        });

        rbtnPython.setText("Python");
        rbtnPython.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnPythonStateChanged(evt);
            }
        });

        rbtnCSharp.setText("C#");
        rbtnCSharp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnCSharpStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnPython)
                            .addComponent(btnConferir, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(rbtnJava)
                .addGap(92, 92, 92)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnCSharp)
                    .addComponent(rbtnJavaScript))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnJava)
                    .addComponent(rbtnJavaScript))
                .addGap(22, 22, 22)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnPython)
                    .addComponent(rbtnCSharp))
                .addGap(18, 18, 18)
                .addComponent(btnConferir)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConferirActionPerformed
        
        if(rbtnJava.isSelected()){
            String mensagem = "Você está certo, Bom garoto!";
            JOptionPane.showMessageDialog(null, mensagem);
        }
        
        if(rbtnJavaScript.isSelected()){
            String mensagem = "Errouuu!";
                        JOptionPane.showMessageDialog(null, mensagem);
        }
        
        if(rbtnPython.isSelected()){
            String mensagem = "Ok, boa linguagem mas Java é melhor!";
                        JOptionPane.showMessageDialog(null, mensagem);
        }
        
        if(rbtnCSharp.isSelected()){
            String mensagem = "Nops! Java é a melhor do mundo";
                        JOptionPane.showMessageDialog(null, mensagem);
        }
        
        
    }//GEN-LAST:event_btnConferirActionPerformed

    private void rbtnJavaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnJavaStateChanged
        
        if(rbtnJava.isSelected()){
            rbtnJavaScript.setSelected(false);
             rbtnCSharp.setSelected(false);
              rbtnPython.setSelected(false);
        }
        
        if(!rbtnJava.isSelected() && !rbtnPython.isSelected() && !rbtnCSharp.isSelected()){
            rbtnJavaScript.setSelected(true);
            
        }
        
        else if(!rbtnJava.isSelected() && !rbtnJavaScript.isSelected() && !rbtnCSharp.isSelected()){
            rbtnPython.setSelected(true);
            
        }
        
        else if(!rbtnJava.isSelected() && !rbtnJavaScript.isSelected() && !rbtnPython.isSelected()){
            rbtnCSharp.setSelected(true);
            
        }
        
   
        
        
        
        
         
        
        
    }//GEN-LAST:event_rbtnJavaStateChanged

    private void rbtnJavaScriptStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnJavaScriptStateChanged
        
        if(rbtnJavaScript.isSelected()){
            rbtnJava.setSelected(false);
             rbtnCSharp.setSelected(false);
              rbtnPython.setSelected(false);
        }
        
        if(!rbtnJavaScript.isSelected() && !rbtnPython.isSelected() && !rbtnCSharp.isSelected()){
            rbtnJava.setSelected(true);
            
        }
        
        else if(!rbtnJavaScript.isSelected() && !rbtnJava.isSelected() && !rbtnCSharp.isSelected()){
            rbtnPython.setSelected(true);
            
        }
        
        else if(!rbtnJava.isSelected() && !rbtnJavaScript.isSelected() && !rbtnPython.isSelected()){
            rbtnCSharp.setSelected(true);
            
        }
        

        
        
     
        
    }//GEN-LAST:event_rbtnJavaScriptStateChanged

    private void rbtnPythonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnPythonStateChanged
        
        if(rbtnPython.isSelected()){
            rbtnCSharp.setSelected(false);
            rbtnJava.setSelected(false);
             rbtnJavaScript.setSelected(false);
             
        }
        
        
         if(!rbtnPython.isSelected() && !rbtnJavaScript.isSelected() && !rbtnJava.isSelected()){
            rbtnCSharp.setSelected(true);
            
        }
        
        else if(!rbtnPython.isSelected() && !rbtnJava.isSelected() && !rbtnCSharp.isSelected()){
            rbtnJavaScript.setSelected(true);
            
        }
        
        else if(!rbtnPython.isSelected() && !rbtnJavaScript.isSelected() && !rbtnCSharp.isSelected()){
            rbtnJava.setSelected(true);
            
        }
        
        

        
     
        
        
    }//GEN-LAST:event_rbtnPythonStateChanged

    private void rbtnCSharpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnCSharpStateChanged
        
        if(rbtnCSharp.isSelected()){
            rbtnPython.setSelected(false);
            rbtnJava.setSelected(false);
            rbtnJavaScript.setSelected(false);
        }
        
        
         if(!rbtnCSharp.isSelected() && !rbtnJavaScript.isSelected() && !rbtnJava.isSelected()){
            rbtnPython.setSelected(true);
            
        }
        
        else if(!rbtnCSharp.isSelected() && !rbtnJava.isSelected() && !rbtnPython.isSelected()){
            rbtnJavaScript.setSelected(true);
            
        }
        
        else if(!rbtnCSharp.isSelected() && !rbtnJavaScript.isSelected() && !rbtnPython.isSelected()){
            rbtnJava.setSelected(true);
            
        }
        

        
       
        
        
    }//GEN-LAST:event_rbtnCSharpStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAula13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAula13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAula13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAula13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAula13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferir;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JRadioButton rbtnCSharp;
    private javax.swing.JRadioButton rbtnJava;
    private javax.swing.JRadioButton rbtnJavaScript;
    private javax.swing.JRadioButton rbtnPython;
    // End of variables declaration//GEN-END:variables
}
