/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aula15_Desafio;

import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaCalculadoraCidadao extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaCalculadoraCidadao() {
        initComponents();
        new atualizaHora().start();
        saidaHora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        pnlRight = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        pnlSimbolo = new javax.swing.JPanel();
        lblSimbolo = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        txtTitulo1 = new javax.swing.JLabel();
        txtTitulo2 = new javax.swing.JLabel();
        pnlHoraData = new javax.swing.JPanel();
        lblData = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        lblPropriedades = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        pnlTabela01 = new javax.swing.JPanel();
        pnlAplicacaoRegular = new javax.swing.JPanel();
        lblNumMeses = new javax.swing.JLabel();
        txtNumMeses = new javax.swing.JTextField();
        lblTaxasJurosMes = new javax.swing.JLabel();
        txtTaxaJuros = new javax.swing.JTextField();
        lblValorDepRegular = new javax.swing.JLabel();
        txtValorDepRegular = new javax.swing.JTextField();
        lblValorFinalPeriodo = new javax.swing.JLabel();
        txtValorFinalPeriodo = new javax.swing.JTextField();
        pnlBotoesDepRegular = new javax.swing.JPanel();
        btnLimpar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        pnlTabela02 = new javax.swing.JPanel();
        pnlFinanciamento = new javax.swing.JPanel();
        lblNumMesesF = new javax.swing.JLabel();
        txtNumMesesF = new javax.swing.JTextField();
        lbTaxasJurosMesF = new javax.swing.JLabel();
        txtTaxasJurosMesF = new javax.swing.JTextField();
        lblValorPresF = new javax.swing.JLabel();
        txtValorPresF = new javax.swing.JTextField();
        lblValorFinanciado = new javax.swing.JLabel();
        txtValorFinanciado = new javax.swing.JTextField();
        pnlBotoesFinanciamento = new javax.swing.JPanel();
        btnVoltarF = new javax.swing.JButton();
        btnLimparF = new javax.swing.JButton();
        btnCalcularF = new javax.swing.JButton();
        btnProximoF = new javax.swing.JButton();
        pnlTabela03 = new javax.swing.JPanel();
        pnlCapital = new javax.swing.JPanel();
        lblNumMesC = new javax.swing.JLabel();
        txtNumMesC = new javax.swing.JTextField();
        lblTaxaJurosMesC = new javax.swing.JLabel();
        txtTaxaJurosMesC = new javax.swing.JTextField();
        lblCapital = new javax.swing.JLabel();
        txtCapital = new javax.swing.JTextField();
        lblValorCapitalFinal = new javax.swing.JLabel();
        txtValorCapitalFinal = new javax.swing.JTextField();
        pnlBotoesCapital = new javax.swing.JPanel();
        btnVoltarC = new javax.swing.JButton();
        btnLimparC = new javax.swing.JButton();
        btnCalcularC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBase.setLayout(new java.awt.BorderLayout());

        pnlLeft.setPreferredSize(new java.awt.Dimension(70, 227));

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        pnlBase.add(pnlLeft, java.awt.BorderLayout.LINE_START);

        pnlRight.setPreferredSize(new java.awt.Dimension(70, 227));

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        pnlBase.add(pnlRight, java.awt.BorderLayout.LINE_END);

        pnlTop.setPreferredSize(new java.awt.Dimension(100, 70));

        lblSimbolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aula15_Desafio/Imagens/money64.png"))); // NOI18N

        javax.swing.GroupLayout pnlSimboloLayout = new javax.swing.GroupLayout(pnlSimbolo);
        pnlSimbolo.setLayout(pnlSimboloLayout);
        pnlSimboloLayout.setHorizontalGroup(
            pnlSimboloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSimboloLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblSimbolo)
                .addContainerGap())
        );
        pnlSimboloLayout.setVerticalGroup(
            pnlSimboloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSimboloLayout.createSequentialGroup()
                .addComponent(lblSimbolo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlTitulo.setLayout(new java.awt.GridLayout(2, 0, 0, 4));

        txtTitulo1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo1.setText("CALCULADORA CIDADÃO");
        txtTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTitulo.add(txtTitulo1);

        txtTitulo2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo2.setText("Selecione a opção de calculo através das abas abaixo");
        txtTitulo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTitulo.add(txtTitulo2);

        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setText("Data");

        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("Hora");

        javax.swing.GroupLayout pnlHoraDataLayout = new javax.swing.GroupLayout(pnlHoraData);
        pnlHoraData.setLayout(pnlHoraDataLayout);
        pnlHoraDataLayout.setHorizontalGroup(
            pnlHoraDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoraDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHoraDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
        );
        pnlHoraDataLayout.setVerticalGroup(
            pnlHoraDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoraDataLayout.createSequentialGroup()
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHoraData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addComponent(pnlHoraData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52))
                    .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(pnlSimbolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlBase.add(pnlTop, java.awt.BorderLayout.PAGE_START);

        pnlBottom.setPreferredSize(new java.awt.Dimension(100, 50));

        lblPropriedades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPropriedades.setText("SENAC 2024 - © Desenvolvido pela turma TDS23-2 - Manhã - Todos os direitos reservados");

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(lblPropriedades, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lblPropriedades)
                .addContainerGap())
        );

        pnlBase.add(pnlBottom, java.awt.BorderLayout.PAGE_END);

        pnlAplicacaoRegular.setLayout(new java.awt.GridLayout(8, 1, 1, 2));

        lblNumMeses.setText("Número Meses");
        pnlAplicacaoRegular.add(lblNumMeses);
        pnlAplicacaoRegular.add(txtNumMeses);

        lblTaxasJurosMes.setText("Taxa de Juros Mensal");
        pnlAplicacaoRegular.add(lblTaxasJurosMes);
        pnlAplicacaoRegular.add(txtTaxaJuros);

        lblValorDepRegular.setText("Valor do Depósito Regular:");
        pnlAplicacaoRegular.add(lblValorDepRegular);
        pnlAplicacaoRegular.add(txtValorDepRegular);

        lblValorFinalPeriodo.setText("Valor Obtido ao Final do Período");
        pnlAplicacaoRegular.add(lblValorFinalPeriodo);
        pnlAplicacaoRegular.add(txtValorFinalPeriodo);

        pnlBotoesDepRegular.setLayout(new java.awt.GridLayout(1, 3, 3, 3));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        pnlBotoesDepRegular.add(btnLimpar);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        pnlBotoesDepRegular.add(btnCalcular);

        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        pnlBotoesDepRegular.add(btnProximo);

        javax.swing.GroupLayout pnlTabela01Layout = new javax.swing.GroupLayout(pnlTabela01);
        pnlTabela01.setLayout(pnlTabela01Layout);
        pnlTabela01Layout.setHorizontalGroup(
            pnlTabela01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabela01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabela01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAplicacaoRegular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlTabela01Layout.createSequentialGroup()
                        .addGap(0, 349, Short.MAX_VALUE)
                        .addComponent(pnlBotoesDepRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlTabela01Layout.setVerticalGroup(
            pnlTabela01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabela01Layout.createSequentialGroup()
                .addComponent(pnlAplicacaoRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotoesDepRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Aplicação Depósitos Regulares", pnlTabela01);

        pnlFinanciamento.setLayout(new java.awt.GridLayout(8, 1, 1, 2));

        lblNumMesesF.setText("Nº. de meses");
        pnlFinanciamento.add(lblNumMesesF);
        pnlFinanciamento.add(txtNumMesesF);

        lbTaxasJurosMesF.setText("Taxa de juros mensal");
        pnlFinanciamento.add(lbTaxasJurosMesF);
        pnlFinanciamento.add(txtTaxasJurosMesF);

        lblValorPresF.setText("Valor da prestação");
        pnlFinanciamento.add(lblValorPresF);
        pnlFinanciamento.add(txtValorPresF);

        lblValorFinanciado.setText("Valor financiado");
        pnlFinanciamento.add(lblValorFinanciado);
        pnlFinanciamento.add(txtValorFinanciado);

        pnlBotoesFinanciamento.setPreferredSize(new java.awt.Dimension(279, 31));
        pnlBotoesFinanciamento.setLayout(new java.awt.GridLayout(1, 3, 1, 1));

        btnVoltarF.setText("Voltar");
        btnVoltarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarFActionPerformed(evt);
            }
        });
        pnlBotoesFinanciamento.add(btnVoltarF);

        btnLimparF.setText("Limpar");
        btnLimparF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFActionPerformed(evt);
            }
        });
        pnlBotoesFinanciamento.add(btnLimparF);

        btnCalcularF.setText("Calcular");
        btnCalcularF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularFActionPerformed(evt);
            }
        });
        pnlBotoesFinanciamento.add(btnCalcularF);

        btnProximoF.setText("Próximo");
        btnProximoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoFActionPerformed(evt);
            }
        });
        pnlBotoesFinanciamento.add(btnProximoF);

        javax.swing.GroupLayout pnlTabela02Layout = new javax.swing.GroupLayout(pnlTabela02);
        pnlTabela02.setLayout(pnlTabela02Layout);
        pnlTabela02Layout.setHorizontalGroup(
            pnlTabela02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabela02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFinanciamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabela02Layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(pnlBotoesFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        pnlTabela02Layout.setVerticalGroup(
            pnlTabela02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabela02Layout.createSequentialGroup()
                .addComponent(pnlFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotoesFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Financiamento Prestações Fixas", pnlTabela02);

        pnlCapital.setLayout(new java.awt.GridLayout(8, 1, 1, 2));

        lblNumMesC.setText("Número de Meses");
        pnlCapital.add(lblNumMesC);
        pnlCapital.add(txtNumMesC);

        lblTaxaJurosMesC.setText("Taxa de Juros Mensal");
        pnlCapital.add(lblTaxaJurosMesC);
        pnlCapital.add(txtTaxaJurosMesC);

        lblCapital.setText("Capital atual");
        pnlCapital.add(lblCapital);
        pnlCapital.add(txtCapital);

        lblValorCapitalFinal.setText("Valor obtido ao final");
        pnlCapital.add(lblValorCapitalFinal);
        pnlCapital.add(txtValorCapitalFinal);

        pnlBotoesCapital.setLayout(new java.awt.GridLayout(1, 3, 1, 2));

        btnVoltarC.setText("Voltar");
        btnVoltarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCActionPerformed(evt);
            }
        });
        pnlBotoesCapital.add(btnVoltarC);

        btnLimparC.setText("Limpar");
        btnLimparC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCActionPerformed(evt);
            }
        });
        pnlBotoesCapital.add(btnLimparC);

        btnCalcularC.setText("Calcular");
        btnCalcularC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCActionPerformed(evt);
            }
        });
        pnlBotoesCapital.add(btnCalcularC);

        javax.swing.GroupLayout pnlTabela03Layout = new javax.swing.GroupLayout(pnlTabela03);
        pnlTabela03.setLayout(pnlTabela03Layout);
        pnlTabela03Layout.setHorizontalGroup(
            pnlTabela03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCapital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabela03Layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addComponent(pnlBotoesCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        pnlTabela03Layout.setVerticalGroup(
            pnlTabela03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabela03Layout.createSequentialGroup()
                .addComponent(pnlCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotoesCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Valor Futuro da Capital", pnlTabela03);

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pnlBase.add(pnlCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        //Capturar os valores que são digitados pelo usuário
        try {

            Double numeroMeses = Double.parseDouble(txtNumMeses.getText());
            Double taxaJurosMensal = Double.parseDouble(txtTaxaJuros.getText());
            Double valorDepRegular = Double.parseDouble(txtValorDepRegular.getText());
            Double valorObtidoFinal;

            Calculadora oper = new Calculadora();
            valorObtidoFinal = oper.calcAplicDepositosReg(numeroMeses, taxaJurosMensal, valorDepRegular);

            txtValorFinalPeriodo.setText(String.valueOf(valorObtidoFinal));

        } catch (Exception e) {

            String mensagem = "Valor inserido não válido ou abas preenchidas incorretamente *preencha as 3 primeiras*";

            JOptionPane.showMessageDialog(null, mensagem);

            txtNumMeses.setText("");
            txtTaxaJuros.setText("");
            txtValorDepRegular.setText("");
            txtValorFinalPeriodo.setText("");

        }


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        txtNumMeses.setText("");
        txtTaxaJuros.setText("");
        txtValorDepRegular.setText("");
        txtValorFinalPeriodo.setText("");


    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCalcularFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularFActionPerformed

        try {

            Double numeroMeses = Double.parseDouble(txtNumMesesF.getText());
            Double taxaJurosMensal = Double.parseDouble(txtTaxasJurosMesF.getText());
            Double valorPres = Double.parseDouble(txtValorPresF.getText());
            Double valorObtidoFinal;

            CalculadoraFinanciamento oper = new CalculadoraFinanciamento();
            valorObtidoFinal = oper.calculoFinanciamento(numeroMeses, taxaJurosMensal, valorPres);

            txtValorFinanciado.setText(String.valueOf(valorObtidoFinal));

        } catch (Exception e) {
            String mensagem = "Valor inserido não válido ou abas preenchidas incorretamente *preencha as 3 primeiras*";

            JOptionPane.showMessageDialog(null, mensagem);
            txtNumMesesF.setText("");
            txtTaxasJurosMesF.setText("");
            txtValorPresF.setText("");
            txtValorFinanciado.setText("");

            //grabFocus
        }
    }//GEN-LAST:event_btnCalcularFActionPerformed

    private void btnLimparFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFActionPerformed
        txtNumMesesF.setText("");
        txtTaxasJurosMesF.setText("");
        txtValorPresF.setText("");
        txtValorFinanciado.setText("");
    }//GEN-LAST:event_btnLimparFActionPerformed

    private void btnCalcularCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCActionPerformed
        try {

            Double numeroMeses = Double.parseDouble(txtNumMesC.getText());
            Double taxaJurosMensal = Double.parseDouble(txtTaxaJurosMesC.getText());
            Double valorPres = Double.parseDouble(txtCapital.getText());
            Double valorObtidoFinal;

            CalcularCapital oper = new CalcularCapital();
            valorObtidoFinal = oper.calcularCapital(numeroMeses, taxaJurosMensal, valorPres);

            txtValorCapitalFinal.setText(String.valueOf(valorObtidoFinal));

        } catch (Exception e) {
            String mensagem = "Valor inserido não válido ou abas preenchidas incorretamente *preencha as 3 primeiras*";

            JOptionPane.showMessageDialog(null, mensagem);
            txtNumMesC.setText("");
            txtTaxaJurosMesC.setText("");
            txtCapital.setText("");
            txtValorCapitalFinal.setText("");

            //grabFocus  
        }


    }//GEN-LAST:event_btnCalcularCActionPerformed

    private void btnLimparCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCActionPerformed
        txtNumMesC.setText("");
        txtTaxaJurosMesC.setText("");
        txtCapital.setText("");
        txtValorCapitalFinal.setText("");
    }//GEN-LAST:event_btnLimparCActionPerformed

    private void btnVoltarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCActionPerformed
        jTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_btnVoltarCActionPerformed

    private void btnVoltarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarFActionPerformed
        jTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_btnVoltarFActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        jTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnProximoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoFActionPerformed
        jTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_btnProximoFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadoraCidadao().setVisible(true);
            }
        });
    }

    //  Criar uma classe para operações com threads
    public class atualizaHora extends Thread {

        public void run() {
            while (true) {
                LocalDateTime hojeAgora = LocalDateTime.now();
                DateTimeFormatter formHora = DateTimeFormatter.ofPattern("HH:mm:ss");
                DateTimeFormatter formData = DateTimeFormatter.ofPattern("EEEE, dd/MM/yyyy");
                lblData.setText(hojeAgora.format(formHora));
                lblHora.setText(hojeAgora.format(formData));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(TelaCalculadoraCidadao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }

    public void saidaHora() {
        LocalTime hojeAgora = LocalTime.now();
        LocalTime horaSaida = LocalTime.of(11, 30);
        if(hojeAgora.isAfter(horaSaida)) {
            JOptionPane.showMessageDialog(null, "Fim de aula! Salve seus arquivos, desligue o PC, organize a bancada e até amanhã");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcularC;
    private javax.swing.JButton btnCalcularF;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimparC;
    private javax.swing.JButton btnLimparF;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnProximoF;
    private javax.swing.JButton btnVoltarC;
    private javax.swing.JButton btnVoltarF;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel lbTaxasJurosMesF;
    private javax.swing.JLabel lblCapital;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNumMesC;
    private javax.swing.JLabel lblNumMeses;
    private javax.swing.JLabel lblNumMesesF;
    private javax.swing.JLabel lblPropriedades;
    private javax.swing.JLabel lblSimbolo;
    private javax.swing.JLabel lblTaxaJurosMesC;
    private javax.swing.JLabel lblTaxasJurosMes;
    private javax.swing.JLabel lblValorCapitalFinal;
    private javax.swing.JLabel lblValorDepRegular;
    private javax.swing.JLabel lblValorFinalPeriodo;
    private javax.swing.JLabel lblValorFinanciado;
    private javax.swing.JLabel lblValorPresF;
    private javax.swing.JPanel pnlAplicacaoRegular;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlBotoesCapital;
    private javax.swing.JPanel pnlBotoesDepRegular;
    private javax.swing.JPanel pnlBotoesFinanciamento;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlCapital;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlFinanciamento;
    private javax.swing.JPanel pnlHoraData;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlSimbolo;
    private javax.swing.JPanel pnlTabela01;
    private javax.swing.JPanel pnlTabela02;
    private javax.swing.JPanel pnlTabela03;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTextField txtCapital;
    private javax.swing.JTextField txtNumMesC;
    private javax.swing.JTextField txtNumMeses;
    private javax.swing.JTextField txtNumMesesF;
    private javax.swing.JTextField txtTaxaJuros;
    private javax.swing.JTextField txtTaxaJurosMesC;
    private javax.swing.JTextField txtTaxasJurosMesF;
    private javax.swing.JLabel txtTitulo1;
    private javax.swing.JLabel txtTitulo2;
    private javax.swing.JTextField txtValorCapitalFinal;
    private javax.swing.JTextField txtValorDepRegular;
    private javax.swing.JTextField txtValorFinalPeriodo;
    private javax.swing.JTextField txtValorFinanciado;
    private javax.swing.JTextField txtValorPresF;
    // End of variables declaration//GEN-END:variables
}
