/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aula17;

import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aluno
 */
public class FrmCamposFormatados extends javax.swing.JFrame {

    /**
     * Creates new form FrmCamposFormatados
     */
    //Instanciando a classe Formatador de Campos como
    //variável "global" para acesso em qualquer posição
    //do programa
    FormatadorCampos formatador = new FormatadorCampos();
    
    public FrmCamposFormatados() throws ParseException {
        initComponents();
        //Inicializar os campos com a formatação definida
        formatador.formatarCampoTelefone(ftxtTelefone);
        formatador.formatarCampoPlaca(ftxtPlaca);
        formatador.formatarCampoCNPJ(ftxtCNPJ);
        formatador.formatarCampoTituloEleitor(ftxtTituloEleitor);
        formatador.formatarCampoTelefoneInternacional(ftxtTelefoneInternacional);
        formatador.formatarCampoDataNascimento(ftxtDataNascimento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        pnlSliders = new javax.swing.JPanel();
        lblTituloVermelho = new javax.swing.JLabel();
        sldVermelho = new javax.swing.JSlider();
        lblTituloVerde = new javax.swing.JLabel();
        sldVerde = new javax.swing.JSlider();
        lblTituloAzul = new javax.swing.JLabel();
        sldAzul = new javax.swing.JSlider();
        lblValorSliderVermelho = new javax.swing.JLabel();
        lblValorSliderVerde = new javax.swing.JLabel();
        lblValorSliderAzul = new javax.swing.JLabel();
        pnlBotoes = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        pnlRight = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        pnlCenter = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNomeCompleto = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        ftxtCPF = new javax.swing.JFormattedTextField();
        lblTelefone = new javax.swing.JLabel();
        ftxtTelefone = new javax.swing.JFormattedTextField();
        lblPlaca = new javax.swing.JLabel();
        ftxtPlaca = new javax.swing.JFormattedTextField();
        lblCNPJ = new javax.swing.JLabel();
        ftxtCNPJ = new javax.swing.JFormattedTextField();
        lblTelefoneInternacional = new javax.swing.JLabel();
        ftxtTelefoneInternacional = new javax.swing.JFormattedTextField();
        lblTituloEleitor = new javax.swing.JLabel();
        ftxtTituloEleitor = new javax.swing.JFormattedTextField();
        lblDataNascimento = new javax.swing.JLabel();
        ftxtDataNascimento = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formatador de Campos");

        pnlBase.setLayout(new java.awt.BorderLayout());

        pnlTop.setPreferredSize(new java.awt.Dimension(941, 80));

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Formulário de Campos Formatados - Java - TDS23_2M");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26))
        );

        pnlBase.add(pnlTop, java.awt.BorderLayout.PAGE_START);

        pnlBottom.setPreferredSize(new java.awt.Dimension(941, 170));

        sldVermelho.setMaximum(255);
        sldVermelho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldVermelhoStateChanged(evt);
            }
        });

        sldVerde.setMaximum(255);
        sldVerde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldVerdeStateChanged(evt);
            }
        });

        sldAzul.setMaximum(255);
        sldAzul.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldAzulStateChanged(evt);
            }
        });

        lblValorSliderVermelho.setText("Vermelho");

        lblValorSliderVerde.setText("Verde");

        lblValorSliderAzul.setText("Azul");

        pnlBotoes.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        btnCancelar.setText("Cancelar");
        pnlBotoes.add(btnCancelar);

        btnSalvar.setText("Salvar");
        pnlBotoes.add(btnSalvar);

        javax.swing.GroupLayout pnlSlidersLayout = new javax.swing.GroupLayout(pnlSliders);
        pnlSliders.setLayout(pnlSlidersLayout);
        pnlSlidersLayout.setHorizontalGroup(
            pnlSlidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSlidersLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(pnlSlidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSlidersLayout.createSequentialGroup()
                        .addGroup(pnlSlidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTituloAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlSlidersLayout.createSequentialGroup()
                        .addComponent(sldAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorSliderAzul)
                        .addContainerGap(413, Short.MAX_VALUE))
                    .addGroup(pnlSlidersLayout.createSequentialGroup()
                        .addGroup(pnlSlidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSlidersLayout.createSequentialGroup()
                                .addComponent(sldVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorSliderVerde))
                            .addGroup(pnlSlidersLayout.createSequentialGroup()
                                .addComponent(sldVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorSliderVermelho))
                            .addComponent(lblTituloVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        pnlSlidersLayout.setVerticalGroup(
            pnlSlidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSlidersLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTituloVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(pnlSlidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSlidersLayout.createSequentialGroup()
                        .addGroup(pnlSlidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sldVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorSliderVermelho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTituloVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSlidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sldVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorSliderVerde)))
                    .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlSlidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSlidersLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTituloAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSlidersLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(lblValorSliderAzul)
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlSliders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(318, 318, 318))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addComponent(pnlSliders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlBase.add(pnlBottom, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        pnlBase.add(pnlRight, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        pnlBase.add(pnlLeft, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.GridLayout(8, 2, 2, 0));

        lblNomeCompleto.setText("Nome Completo:");
        jPanel2.add(lblNomeCompleto);
        jPanel2.add(txtNomeCompleto);

        lblCPF.setText("CPF:");
        jPanel2.add(lblCPF);

        try {
            ftxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(ftxtCPF);

        lblTelefone.setText("Telefone");
        jPanel2.add(lblTelefone);
        jPanel2.add(ftxtTelefone);

        lblPlaca.setText("Placa Automóvel");
        jPanel2.add(lblPlaca);
        jPanel2.add(ftxtPlaca);

        lblCNPJ.setText("CNPJ");
        jPanel2.add(lblCNPJ);
        jPanel2.add(ftxtCNPJ);

        lblTelefoneInternacional.setText("Telefone Internacional");
        jPanel2.add(lblTelefoneInternacional);
        jPanel2.add(ftxtTelefoneInternacional);

        lblTituloEleitor.setText("Título Eleitor");
        jPanel2.add(lblTituloEleitor);
        jPanel2.add(ftxtTituloEleitor);

        lblDataNascimento.setText("Data Nascimento");
        jPanel2.add(lblDataNascimento);
        jPanel2.add(ftxtDataNascimento);

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlBase.add(pnlCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBase, javax.swing.GroupLayout.PREFERRED_SIZE, 927, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldVerdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVerdeStateChanged
        atualizaCor();
    }//GEN-LAST:event_sldVerdeStateChanged

    private void sldVermelhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVermelhoStateChanged
        
        atualizaCor();
        
    }//GEN-LAST:event_sldVermelhoStateChanged

    private void sldAzulStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldAzulStateChanged
         atualizaCor();
    }//GEN-LAST:event_sldAzulStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCamposFormatados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCamposFormatados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCamposFormatados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCamposFormatados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmCamposFormatados().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(FrmCamposFormatados.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JFormattedTextField ftxtCNPJ;
    private javax.swing.JFormattedTextField ftxtCPF;
    private javax.swing.JFormattedTextField ftxtDataNascimento;
    private javax.swing.JFormattedTextField ftxtPlaca;
    private javax.swing.JFormattedTextField ftxtTelefone;
    private javax.swing.JFormattedTextField ftxtTelefoneInternacional;
    private javax.swing.JFormattedTextField ftxtTituloEleitor;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTelefoneInternacional;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloAzul;
    private javax.swing.JLabel lblTituloEleitor;
    private javax.swing.JLabel lblTituloVerde;
    private javax.swing.JLabel lblTituloVermelho;
    private javax.swing.JLabel lblValorSliderAzul;
    private javax.swing.JLabel lblValorSliderVerde;
    private javax.swing.JLabel lblValorSliderVermelho;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlSliders;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JSlider sldAzul;
    private javax.swing.JSlider sldVerde;
    private javax.swing.JSlider sldVermelho;
    private javax.swing.JTextField txtNomeCompleto;
    // End of variables declaration//GEN-END:variables

    private void atualizaCor() {
        int valorSliderVermelho = sldVermelho.getValue();
        int valorSliderVerde = sldVerde.getValue();
        int valorSliderAzul = sldAzul.getValue();
        lblTituloVermelho.setText(String.valueOf(valorSliderVermelho));
        lblTituloVerde.setText(String.valueOf(valorSliderVerde));
        lblTituloAzul.setText(String.valueOf(valorSliderAzul));
        
        pnlCenter.setBackground(new Color(valorSliderVermelho, valorSliderVerde, valorSliderAzul));
    }
}


